--
-- PostgreSQL database dump
--

\restrict HhgrfQrsZNOCZwo4xdaPWGhUKaJwRUmQAf3dk7jGmHZlbBck2YrKPHItP1q8tMA

-- Dumped from database version 17.5 (a42a079)
-- Dumped by pg_dump version 17.6

-- Started on 2025-09-16 22:04:20

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3383 (class 0 OID 57405)
-- Dependencies: 226
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.product (product_id, product_name, description, price, inventory, prod_image_url, fk_category_id) FROM stdin;
1	Whimsigoth Sun Auburn and Green Beaded Necklace with Leaf Accents in Silver| Celestial | Whimsitwee | 	This necklace is semi stainless steel with beautiful green and auburn glass beads. Handmade and lightweight.	19.99	10	https://i.etsystatic.com/34112083/r/il/539f2a/6890133850/il_794xN.6890133850_rlmr.jpg	\N
2	Whimsigoth Sun Auburn and Green Beaded Necklace with Leaf Accents in Silver| Celestial | Whimsitwee | 	This necklace is semi stainless steel with beautiful green and auburn glass beads. Handmade and lightweight.	19.99	10	https://i.etsystatic.com/34112083/r/il/539f2a/6890133850/il_794xN.6890133850_rlmr.jpg	\N
5	Triple Moon Goddess necklace | Pagan | Pentacle/ Pentagram Moon Charm Wicca jewelry	This is a simple necklace with a pentacle moon trinity charm in silver tone with an adjustable cord necklace- will complete any look and is perfect as a necklace duo or stand alone.   Fast shipping and perfect for any occasion.  We offer matching earrings— see shop for listing.	10.00	1	https://i.etsystatic.com/34112083/r/il/5faf1f/3749917486/il_fullxfull.3749917486_eunl.jpg	\N
6	Whimsigoth beaded rose Flower Dangling Earrings in Bronze| Fairycore | Whimsical	These dangling earrings are made with champagne and black beads with bronze rose flower charm.  These are dainty mid-weight, easy to wear and so beautiful:) made with a lever back hook style for convenience-  Perfect for any day wear or a special occasion. We ship as fast as possible.	14.75	1	https://i.etsystatic.com/34112083/r/il/417671/7252702817/il_fullxfull.7252702817_ikql.jpg	\N
7	Whimsigoth Moon and Stars champagne Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind natural earth tones champagne beaded necklace with bronze crescent moon pendent and accent stars! The delicate champagne and bronze combination is beautiful and creatively unique. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-18 inches	16.25	1	https://i.etsystatic.com/34112083/r/il/bbdf39/7252541293/il_fullxfull.7252541293_2xex.jpg	\N
8	Whimsigoth Green daisy pendant Beaded necklace in green, champagne and Bronze | Fairycore | Whimsicle | naturalist |	This dainty necklace is a one of a kind green and iridescent beaded bronze necklace choker! The beaded design and bronze combination is beautiful.   Necklace is complete with our popular flower  pendent charm-This necklace is handmade and quick shipping!  Pendant size— .60 inch  Each necklace will have different unique color variations and sizes - Around 15.5-17 inches	15.75	1	https://i.etsystatic.com/34112083/r/il/b8aed7/7015505131/il_fullxfull.7015505131_s6bk.jpg	\N
9	Bronze earth tones beaded necklace with dragonfly daisy  design  | Fairycore | Whimsicle | naturalist |	This is a one of a kind earth tones  beaded necklace choker! The beaded design of champagne and brown with daisy beads on bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 15.5-17 inches	18.50	1	https://i.etsystatic.com/34112083/r/il/68132e/7067136474/il_fullxfull.7067136474_tb2u.jpg	\N
10	Whimsigoth Auburn Dragonfly Beaded Bracelet in Bronze | Cottagecore | Whimsitwee	This beaded bracelet is matching with one of our most popular beaded necklace. The Auburn and bronze is a unique combination of colors. Nickel free alloy.  Length— 8in plus extender	14.50	1	https://i.etsystatic.com/34112083/r/il/486cf5/7078486936/il_fullxfull.7078486936_9sf7.jpg	\N
11	Whimsigoth Fall Maple Leaves  Beaded Necklace in Bronze | Goblincore | Cottagecore |	This necklace is a beautiful mix of bronze metal and orange brown beads. The metal is bronze alloy so keep away from high moisture areas. The necklace length is between 16-17 inches.	19.75	1	https://i.etsystatic.com/34112083/r/il/1d362d/7186416787/il_fullxfull.7186416787_pedj.jpg	\N
12	Whimsigoth Dragonfly Auburn Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	—-Option to add earrings, bracelet—- This is a one of a kind auburn beaded necklace choker! The beaded design and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 15.5-17 inches	19.75	1	https://i.etsystatic.com/34112083/r/il/7d399d/6670834165/il_fullxfull.6670834165_8hz0.jpg	\N
13	Collide With The Sky Inspired Earrings | PTV | Emo | Alternative Jewelry |	These earrings are inspired by the Collide With The Sky album by Pierce The Veil. The silver and Black tones match the albums vibe seamlessly. Stainless Steel Silver and ready to ship!   Charm Length— 2-2.75 Inches  —The charm used is PLA 3D printed with a resin topcoat to keep it shiny— -EACH PAIR OF EARRINGS IS UNIQUE IN SHAPE AND COLOR DUE TO IT BEING HANDMADE! PLEASE BE MINDFUL BEFORE PURCHASING	16.50	1	https://i.etsystatic.com/34112083/r/il/e9ab2d/7077859230/il_fullxfull.7077859230_5fks.jpg	\N
14	Whimsigoth Sun Auburn Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind auburn beaded necklace choker! The brown and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-17 inches	19.75	1	https://i.etsystatic.com/34112083/r/il/7caed7/7082321991/il_fullxfull.7082321991_aweu.jpg	\N
15	Silver Skeleton Hand Cord Pendant Necklace | Gothic | Alternative	This necklace is a beautiful mix of silver and black tones. Lightweight and comfortable for any occasion. Nickel free alloy so keep away from areas with high moisture.  Length 18-19 inches	10.00	1	https://i.etsystatic.com/34112083/r/il/aceac5/6487998545/il_fullxfull.6487998545_h50v.jpg	\N
16	Collide With The Sky Inspired Keychain | Emo | Scene | PTV | Punk	ONE KEYCHAIN PER PURCHASE— Pierce the Veil Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat— Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.50	1	https://i.etsystatic.com/34112083/r/il/3a9ddd/7125814921/il_fullxfull.7125814921_k06n.jpg	\N
17	Welcome To Black Parade Inspired Earrings | MCR | Emo | Alternative Jewelry |	These earrings are inspired by the Welcome to the Black Parade album by My Chemical Romance. The silver and Black tones match the albums vibe seamlessly. Stainless Steel Silver and ready to ship!   Charm Length— 2.68-3 Inches  —The charm used is PLA 3D printed with a resin topcoat to keep it shiny— -EACH PAIR OF EARRINGS IS UNIQUE IN SHAPE AND COLOR DUE TO IT BEING HANDMADE! PLEASE BE MINDFUL BEFORE PURCHASING	16.50	1	https://i.etsystatic.com/34112083/r/il/9ce879/7125788793/il_fullxfull.7125788793_mp11.jpg	\N
18	Three Cheers for Sweet Revenge Inspired Mismatch Earrings | Emo | Scene | Punk	Three Cheers for Sweet Revenge  Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat—  Size— 1.25 inch charms Super lightweight and a unique mismatch duo design.	16.75	1	https://i.etsystatic.com/34112083/r/il/b57a1a/7223872527/il_fullxfull.7223872527_dkxu.jpg	\N
19	Pentacle/ Pentagram Cord Necklace in Gold or Bronze |Pagan | Celtic Pagan | Witchcraft | Norse |	This is a simple charmed pentacle necklace with cord. This is made for anyone and it’s easy to wear with free shipping! It’s lightweight and can be customized if you message us!	10.00	1	https://i.etsystatic.com/34112083/r/il/8f2881/4455820841/il_fullxfull.4455820841_48ki.jpg	\N
20	Whimsigoth Sun Auburn and Green Beaded Necklace with Leaf Accents in Silver| Celestial | Whimsitwee |	This necklace is semi stainless steel with beautiful green and auburn glass beads. Handmade and lightweight. Jewelry Care! Keep away from moisture and water to keep metal from tarnish 💚	17.50	1	https://i.etsystatic.com/34112083/r/il/539f2a/6890133850/il_fullxfull.6890133850_rlmr.jpg	\N
21	Welcome to the Black Parade Inspired Keychain | Emo | Scene | Punk | MCR |	ONE KEYCHAIN PER PURCHASE— Welcome to the Back Parade Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat— Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.50	1	https://i.etsystatic.com/34112083/r/il/c2bcab/7020325588/il_fullxfull.7020325588_pmp6.jpg	\N
22	Whimsigoth Brass Moon Pendant with 18k Gold Plated Heart Locket | Sodalite Beaded Necklace | Whimsitwee | Cottagecore	The mix of gold and blue is a perfect match for a whimsigoth style. Keep necklace away from moisture to retain the gorgeous gold color!  Heart Locket— 8mm  Length: 16-18 inches	20.00	1	https://i.etsystatic.com/34112083/r/il/d3a0a4/7198404114/il_fullxfull.7198404114_9xfm.jpg	\N
23	Whimsigoth Floral Pink Tulip Dangling Necklace 18k Gold Stainless Steel Plated | Fairycore | Cottagecore	This are chandelier style with an acrylic lily flower. This necklace is 18k gold stainless steel plated which means it is tarnish resistant! These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	12.00	1	https://i.etsystatic.com/34112083/r/il/a5a97d/5634882818/il_fullxfull.5634882818_qpx9.jpg	\N
24	Whimsigoth Sodalite Crystal Heart Pendant Necklace with Stainless Steel Chain	Free shipping on orders over $35  This is our sodalite heart crystal necklace in silver tone. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  Length- 18”   The stone pendants are natural so each crystal varies in color and overall shape.	14.50	1	https://i.etsystatic.com/34112083/r/il/feb2df/5655271652/il_fullxfull.5655271652_klox.jpg	\N
25	Whimsigoth Red Jasper Crystal Heart Pendant Necklace with Stainless Steel Chain	Free shipping on orders over $35  This is our Jasper heart crystal necklace in silver tone. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  Length- 18”   The stone pendants are natural so each crystal varies in color and overall shape.	14.50	1	https://i.etsystatic.com/34112083/r/il/e2f278/5703326819/il_fullxfull.5703326819_ejhi.jpg	\N
26	Collide With The Sky Inspired cord Necklace | PTV | Pierce The Veil | Emo | Alternative Jewelry |	This is a cord necklace inspired by the Collide with the Sky album by Pierce The Veil. The silver and Black tones match the albums vibe seamlessly. Nickel free and ready to ship!  Necklace Length: 17-18 inches Charm Length— 2-2.75 Inches —The charm used is PLA 3D printed with a resin topcoat to keep it shiny— -EACH NECKLACE IS UNIQUE IN SHAPE AND COLOR DUE TO IT BEING HANDMADE! PLEASE BE MINDFUL BEFORE PURCHASING	17.50	1	https://i.etsystatic.com/34112083/r/il/4afb35/7125794125/il_fullxfull.7125794125_k6jq.jpg	\N
27	Whimsigoth Songbird Beaded Necklace Choker in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind beaded necklace ! The auburn and green agate combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 15-16 inches	21.50	1	https://i.etsystatic.com/34112083/r/il/8e667d/7087331755/il_fullxfull.7087331755_e18n.jpg	\N
28	Collide With The Sky Inspired Beaded Keychain | Emo | Scene | Punk | PTV |	ONE KEYCHAIN PER PURCHASE— Pierce the Veil Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat— Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	14.55	1	https://i.etsystatic.com/34112083/r/il/df4d5f/7077864610/il_fullxfull.7077864610_hbby.jpg	\N
29	Three Cheers for Sweet Revenge Inspired Magnetic Duo Cord Necklace | MCR | Friendship Necklace | Couples Jewelry |	Magnetic Duo Friendship/ Couples Necklace. This is a cord necklace inspired by the Welcome to the Black Parade album by Three Cheers for Sweet Revenge. The silver and Black tones match the albums vibe seamlessly. Nickel free and ready to ship!  Necklace Length: 17-18 inches Charm Length— 2.68-3 Inches —The charm used is PLA 3D printed with a resin topcoat to keep it shiny— -EACH NECKLACE IS UNIQUE IN SHAPE AND COLOR DUE TO IT BEING HANDMADE! PLEASE BE MINDFUL BEFORE PURCHASING	30.50	1	https://i.etsystatic.com/34112083/r/il/53afc0/7241654077/il_fullxfull.7241654077_5i0l.jpg	\N
30	Whimsigoth Fall Maple Leaves Mushroom Beaded Necklace in Bronze | Goblincore | Cottagecore |	This necklace is a beautiful mix of bronze metal and orange brown beads. The metal is bronze alloy so keep away from high moisture areas.  The necklace length is between 16-17 inches.	24.00	1	https://i.etsystatic.com/34112083/r/il/0c5322/7039343356/il_fullxfull.7039343356_4i58.jpg	\N
31	Whimsigoth Purple Trumpet Flower Chandelier Earrings | Goth | Whimsical | Fairycore | Grunge	These Earrings are lightweight and comfortable to wear. Gauged ear friendly 💚 Lever back earrings for comfortable fit.	16.55	1	https://i.etsystatic.com/34112083/r/il/0c1c0f/6877182415/il_fullxfull.6877182415_i9ek.jpg	\N
32	Whimsigoth Bronze Birdskull Floral Ankh Keychain | Whimsitwee | Gothic |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.00	1	https://i.etsystatic.com/34112083/r/il/019b3c/6912788508/il_fullxfull.6912788508_o5t2.jpg	\N
33	Whimsigoth Bronze Maple Leaf Floral Keychain | Whimsitwee | Gothic |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.00	1	https://i.etsystatic.com/34112083/r/il/6a2907/6960779061/il_fullxfull.6960779061_nwho.jpg	\N
34	Silver Angel Earrings | Fairy | Whimsigoth |	These Earrings are a beautiful mix of pearl and rose gold. They are lightweight and comfortable to wear. The earrings are made of rose gold alloy and are not tarnish resistant.	6.50	1	https://i.etsystatic.com/34112083/r/il/124d6e/6278534269/il_fullxfull.6278534269_o11e.jpg	\N
35	Three Cheers for Sweet Revenge Inspired Beaded Magnetic Duo Keychain | Emo | Scene | Punk	TWO KEYCHAIN PER PURCHASE— Three Cheers for Sweet Revenge  Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat—  Perfect duo gift for best friends, partners, siblings and etc. The magnetic keychain clicks together when they are paired.	27.75	1	https://i.etsystatic.com/34112083/r/il/54cc2f/7221839817/il_fullxfull.7221839817_92o8.jpg	\N
36	Whimsigoth | Witchcraft | Fairy | Crystal Amethyst Crescent Moon  Necklace in Bronze	This is a beautiful raw amethyst crystal dangling from a crescent moon. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  EACH AMETHYST STONE IS UNIQUE IN SHAPE AND COLOR— PLEASE BE MINDFUL NOT EVERY NECKLACE WILL BE IDENTICAL TO THE SAME AND COLOR OF THE IMAGE SHOWN—	12.00	1	https://i.etsystatic.com/34112083/r/il/7894bc/6547975609/il_fullxfull.6547975609_30nd.jpg	\N
37	Whimsigoth Moon Burgundy Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind burgundy beaded necklace choker! The fed and bronze combination is beautifu. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-18 inches	18.50	1	https://i.etsystatic.com/34112083/r/il/23478a/6753768831/il_fullxfull.6753768831_el47.jpg	\N
38	Whimsigoth Floral Lily of the Valley Flower Dangling 18k Gold Stainless Steel Plated Earrings  | Fairycore | Whimsical	These dangling earrings are chandelier style with an acrylic lily flower. These earrings are 18k gold stainless steel plated These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	16.95	1	https://i.etsystatic.com/34112083/r/il/da4c7d/5424875553/il_fullxfull.5424875553_2hv1.jpg	\N
39	Bronze claddagh pendent beaded necklace/ Celtic chariot exclusive / dark green -Auburn Beaded necklace /celticore / Celtic jewelry	This is a Celtic chariot exclusive design featuring our bronze Claddagh - handmade and created.  Only high quality beads used in colors of rich auburn , dark green , champagne and bronze beads- this is a beaded necklace choker! The brown - green and bronze combination is beautiful. This necklace is unique with quick shipping!  Each necklace may  have different unique color variations and sizes -  Around 16-17 inches  we can make any length just add in notes At checkout!	18.00	1	https://i.etsystatic.com/34112083/r/il/15c600/6952171530/il_fullxfull.6952171530_m9sb.jpg	\N
40	Whimsigoth Purple Trumpet Flower Beaded Necklace in Bronze| Fairycore | Gothic | naturalist |	Option to add earrings …  This is a one of a kind trumpet flower beaded necklace! The trumpet flower is an acrylic material and the beads are acrylic as well.  Keep away from moisture! Length: 17-18in	18.50	1	https://i.etsystatic.com/34112083/r/il/0b8aac/6829475420/il_fullxfull.6829475420_215o.jpg	\N
41	Boho mixed beads, 50 piece set, 3 styles of beads in neutral  tones for jewelry making/ beaded necklace bracelet beads diy	Mixed bead set in neutral tones, browns and tan beads for a diy crafter. Beads include 3 styles of  50 total mixed beads.   - 50 piece set - 3 design styles   - heart rounded bead ,  tribal  oblong beads,  and wood inspired filler design beads for jewelry making/ beaded necklace bracelet beads diy	3.75	1	https://i.etsystatic.com/34112083/r/il/62be7e/6597406843/il_fullxfull.6597406843_repd.jpg	\N
42	Three Cheers for Sweet Revenge Inspired Duo Keychain | Emo | Scene | Punk	TWO KEYCHAIN PER PURCHASE— **NOT MAGNETIC STANDARD KEYCHAIN***   Three Cheers for Sweet Revenge  Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat—  Perfect duo gift for best friends, partners, siblings and etc.	21.50	1	https://i.etsystatic.com/34112083/r/il/25b65d/7174275442/il_fullxfull.7174275442_10ug.jpg	\N
43	Whimsigoth Bronze Sun Deep Auburn Beaded Necklace | Celestial | Whimsical | Vampy Goth |	This necklace is nickel free bronze with beautiful auburn and champagne glass beads. Handmade and lightweight. Jewelry Care! Keep away from moisture and water to keep metal from tarnish 💚	16.50	1	https://i.etsystatic.com/34112083/r/il/7d3f2c/6891336812/il_fullxfull.6891336812_ng4n.jpg	\N
44	Victorian Hummingbird Auburn Trumpet Flower Beaded Necklace in Bronze| Fairycore | Whimsigoth | Whimsitwee |	This is a one of a kind trumpet flower beaded necklace! The trumpet flower is an acrylic material and the beads are acrylic as well.  Keep away from moisture! Length: 15-16in	25.00	1	https://i.etsystatic.com/34112083/r/il/1319d1/7023761955/il_fullxfull.7023761955_17rs.jpg	\N
45	Brass Hand Heart Locket Floral 18k Gold Plated Necklace | Whimsitwee | Whimsigoth | Cottagecore	This necklace is the perfect piece for any loving photo. Pictures of your partner or pet are perfect additions to this heart locket. It is lightweight and semi stainless steel which means the pendant itself is made of a brass while the chain is 18k gold stainless steel.	18.50	1	https://i.etsystatic.com/34112083/r/il/08c4b2/7178069036/il_fullxfull.7178069036_ltfw.jpg	\N
46	Moon Trinity Pentacle earrings-witchcraft jewelry/ pagan/ Celtic/ celestial / tree of life	Pentacle tree of life moon trinity earrings in silver tones as drop earrings-	10.00	1	https://i.etsystatic.com/34112083/r/il/6715d5/5010085534/il_fullxfull.5010085534_3aem.jpg	\N
47	Whimsigoth Bohemian Flower Fall Earrings in Bronze | Fairycore | Whimsical	ONE PAIR ! These are dangling simple and light weigh flowerearrings bronze tones- Resin Floral Pendant   Perfect for any day wear or a special occasion.	10.75	1	https://i.etsystatic.com/34112083/r/il/8836cb/6768356675/il_fullxfull.6768356675_qvfu.jpg	\N
48	Whimsigoth Dragonfly Floral Green  Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind green and iridescent beaded bronze necklace choker! The beaded design and bronze combination is beautiful. Necklace is complete with our popular dragonfly pendent charm-This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 15.5-17 inches	18.75	1	https://i.etsystatic.com/34112083/r/il/90d607/6885722776/il_fullxfull.6885722776_cmm2.jpg	\N
49	Whimsigoth Green Floral  Dragonfly Flower Dangling Earrings in Bronze| Fairycore | Whimsical	These dangling earrings are chandelier style with an acrylic lily flower. These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible.	15.00	1	https://i.etsystatic.com/34112083/r/il/641bb5/6932037585/il_fullxfull.6932037585_j6x3.jpg	\N
50	Whimsitwee Bronze Auburn Flower Cord Necklace | Cottagecore | Whimsigoth | Bohemian	ONLY ONE NECKLACE— This necklace is perfect for anyone! Super lightweight and  resin flower with a bronze pendant!	13.50	1	https://i.etsystatic.com/34112083/r/il/24b5b8/6734031816/il_fullxfull.6734031816_j1pu.jpg	\N
100	Whimsigoth Auburn Sun Beaded Bracelet in Bronze | Cottagecore | Whimsitwee	This beaded bracelet is matching with one of our most popular beaded necklace. The Auburn and bronze is a unique combination of colors. Nickel free alloy.  Length— 8in plus extender	14.50	1	https://i.etsystatic.com/34112083/r/il/992867/7126390947/il_fullxfull.7126390947_6rm6.jpg	\N
51	Welcome to the Black Parade Inspired Silver and Black cord Necklace | MCR | Emo | Alternative Jewelry |	This is a cord necklace inspired by the Welcome to the Black Parade album by My Chemical Romance. The silver and Black tones match the albums vibe seamlessly. Nickel free and ready to ship!  Necklace Length: 17-18 inches Charm Length— 2.68-3 Inches —The charm used is PLA 3D printed with a resin topcoat to keep it shiny— -EACH NECKLACE IS UNIQUE IN SHAPE AND COLOR DUE TO IT BEING HANDMADE! PLEASE BE MINDFUL BEFORE PURCHASING	17.50	1	https://i.etsystatic.com/34112083/r/il/9481a3/7068299767/il_fullxfull.7068299767_jqr2.jpg	\N
52	Natural Butterfly Beaded necklace in Bronze | Fairycore | Whimsigoth | naturalist |	This is a one of a kind beaded necklace choker! The beaded design and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 15.5-17 inches	18.85	1	https://i.etsystatic.com/34112083/r/il/dc7a10/6798948964/il_fullxfull.6798948964_gwhl.jpg	\N
53	Whimsigoth Black Trumpet Flower Chandelier Earrings | Goth | Whimsical | Fairycore | Grunge	These Earrings are lightweight and comfortable to wear. Gauged ear friendly 💚 Lever back earrings for comfortable fit.	16.95	1	https://i.etsystatic.com/34112083/r/il/157621/6587688795/il_fullxfull.6587688795_mb6q.jpg	\N
54	Gothic Hand Baphomet Sword Necklace in bronze | Whimsigoth | Goth | Grunge	This is a one of a kind hand sword beaded necklace ! The green and Bronze combination is super dynamic and pretty. This necklace is handmade and quick shipping! Please be mindful of tarnishing and keep away from moisture!  Each necklace will have different unique color variations and sizes - Around 19-20 inches	18.00	1	https://i.etsystatic.com/34112083/r/il/210cc0/6960795783/il_fullxfull.6960795783_aadj.jpg	\N
55	bohemian beads, 50 piece set, sun design beads for jewelry making/ beaded necklace bracelet beads diy	Resin sun beads— boho inspired design, wood look but resin beads for a diy crafter. Beads include 50 of the same bead.   - 50 piece set  - sun with happy face design /  beads for jewelry making/ beaded necklace bracelet beads diy	5.00	1	https://i.etsystatic.com/34112083/r/il/5d3c3a/6549275174/il_fullxfull.6549275174_aq8f.jpg	\N
56	bohemian beads, 50 piece set, daisy design beads for jewelry making/ beaded necklace bracelet beads diy	bohemian beads for a diy crafter. Beads include 50 of the same bead.   - 50 piece set  - daisy design beads for jewelry making/ beaded necklace bracelet beads diy	3.75	1	https://i.etsystatic.com/34112083/r/il/748ff7/6549155718/il_fullxfull.6549155718_iqiz.jpg	\N
57	Whimsigoth Dragonfly Auburn & Deep Green Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind auburn beaded necklace choker! The beaded design and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 17 inches	18.00	1	https://i.etsystatic.com/34112083/r/il/9ac460/6753778665/il_fullxfull.6753778665_s3lk.jpg	\N
58	Gothic Bronze Bat Keychain with  Brown Accents| Whimsitwee | Gothic |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.00	1	https://i.etsystatic.com/34112083/r/il/543eb0/7156602248/il_fullxfull.7156602248_nc9c.jpg	\N
59	Gothic Bronze Ghost Keychain with Burgundy and Brown Accents| Whimsitwee | Gothic |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.00	1	https://i.etsystatic.com/34112083/r/il/dcc45c/7204590743/il_fullxfull.7204590743_phmt.jpg	\N
60	Whimsigoth Auburn and Aqua Floral Dragonfly Beaded necklace in Bronze | Fairycore | Whimsicle | Whimsitwee |	This is a one of a kind auburn and aqua beaded necklace choker! The beaded design and bronze combination is beautiful. This necklace is handmade and quick shipping!  —Nickel Free Alloy Bronze Each necklace will have different unique color variations and sizes - Around 16-17 inches	28.50	1	https://i.etsystatic.com/34112083/r/il/2b958e/7039151403/il_fullxfull.7039151403_pnhu.jpg	\N
61	Bronze Heart Pendant Beaded Necklace in Auburn | Gothic |Whimsigoth | Artsy | Alternative	This necklace is a perfect piece to pair either on its own or with our other pieces. It is lightweight and comfortable. The bronze and burgundy colors match perfectly to make an elegant appearance.  16-18 inches in length	16.75	1	https://i.etsystatic.com/34112083/r/il/d54f60/6898210391/il_fullxfull.6898210391_7pzd.jpg	\N
62	Whimsigoth Dragonfly Aqua Terra Jasper Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind blue terra Jasper beaded necklace choker! The natural Jasper and bronze combination is beautifu. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-17 inches	18.50	1	https://i.etsystatic.com/34112083/r/il/03eb89/6917571620/il_fullxfull.6917571620_biqu.jpg	\N
63	Whimsigoth Dragonfly green  Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind green and iridescent beaded bronze necklace choker! The beaded design and bronze combination is beautiful. Necklace is complete with our popular dragonfly pendent charm-This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 15.5-17 inches	18.50	1	https://i.etsystatic.com/34112083/r/il/924988/7145314055/il_fullxfull.7145314055_glp4.jpg	\N
64	Whimsigoth Bronze Sun and Moon Keychain with Golden Iridescent Accents| Whimsitwee | Gothic |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.00	1	https://i.etsystatic.com/34112083/r/il/e4cb3d/6960781505/il_fullxfull.6960781505_cf7k.jpg	\N
65	Gothic Hand Baphomet Sword Necklace in Silver Alloy | Whimsigoth | Goth | Grunge	This is a one of a kind hand sword beaded necklace ! The brown and silver combination is super dynamic and pretty. This necklace is handmade and quick shipping! This is a stainless chain but the charms are a nickel free alloy so please be mindful of tarnishing and keep away from moisture!  Each necklace will have different unique color variations and sizes - Around 19-21 inches	20.00	1	https://i.etsystatic.com/34112083/r/il/39ec26/6960793823/il_fullxfull.6960793823_tlis.jpg	\N
66	Fairy Iridescent Aura Beaded Earrings with Star charms | Fairycore | Whimsigoth | Goblincore	These are a dangling style silver toned earrings that are made with light weight acrylic beads and star pendants. Easy to wear and fast shipping!	10.00	1	https://i.etsystatic.com/34112083/r/il/d08ece/5852632971/il_fullxfull.5852632971_5sbs.jpg	\N
67	Ankh earrings- large size- available in bronze gold or silver	Large Ankh pendent dangling earrings with lever back clasps. We offer bronze gold or silver.  The ankh symbol is from ancient Egyptian culture and thought of as “ the key of life “ and represents eternal life. Symbol of healing properties and associated with strength and prosperity, the ankh is said to be the first--or original--cross.  Ready to ship —	12.50	1	https://i.etsystatic.com/34112083/r/il/5b951a/3998501220/il_fullxfull.3998501220_iv7u.jpg	\N
68	Whimsigoth Bronze Floral Lily of the Valley Chandelier Necklace | Whimsical | Floral Jewelry |	Lily of the valley bronze necklace! Beautiful combination of bronze and pearl!  Keep away from high moisture areas  Length 17-18in	18.50	1	https://i.etsystatic.com/34112083/r/il/9000ec/6609277091/il_fullxfull.6609277091_1q1n.jpg	\N
69	Whimsitwee Bouquet Lily of the Valley Flower Dangling Chandilier Earrings in 18k Gold Plated Stainless Steel | Fairycore | Cottagecore	These dangling earrings are chandelier style with an acrylic lily flower.  18k Gold Plated Stainless Steel— Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	17.50	1	https://i.etsystatic.com/34112083/r/il/19dac9/6962590602/il_fullxfull.6962590602_5lj2.jpg	\N
70	Whimsitwee Red Floral Tulip Earrings in Bronze/Gold/Silver | Fairycore | Whimsigoth	These are dangling simple and light weigh maple  earrings in gold tones, silver tones, bronze tones-  Perfect for any day wear or a special occasion.	9.50	1	https://i.etsystatic.com/34112083/r/il/967591/6753788016/il_fullxfull.6753788016_7xg1.jpg	\N
71	Misadventures Inspired Silver and Red Beaded Necklace | PTV | Emo | Alternative Jewelry |	This is a beaded necklace inspired by the Misadventures album by Pierce the Veil. The silver and red tones match the albums vibe seamlessly. Nickel free and ready to ship!  Length: 15-17 inches	22.50	1	https://i.etsystatic.com/34112083/r/il/603fe9/6217923383/il_fullxfull.6217923383_q74a.jpg	\N
72	Whimsigoth Auburn Sun and Moon Beaded Belt in Bronze | Chain Belt | Renaissance | Whimsitwee	This is a beaded belt, perfect to accessorize any outfit. The chain is super lightweight and flowy. Instead of being made from solid leather or fabric, it’s constructed with beads and chain. It can be worn at the waist or hips—sometimes even loosely draped over dresses, tunics, or jeans as an accessory rather than a functional belt.  Length-- 3ft-- Size is adjustable to make smaller  (Can be altered to a bigger size)	36.75	1	https://i.etsystatic.com/34112083/r/il/9763d1/7135439290/il_fullxfull.7135439290_sumh.jpg	\N
73	Strawberry Shortcake Inspired Beaded Necklace with Strawberry Photo Locket | Cottagecore | Whimsitwee | Fairycore	This necklace is a beautiful combination of Pink, Green and Gold. It is lightweight and comfortable to wear. The locket is between 1-1.10inchs long and wide.   — Pictures of loved ones or pets are a great addition to this piece.   —The material used for this piece is nickel free alloy and 18k Gold Stainless steel chain so be mindful to tarnishing and keep away from high moisture areas. Length: 16-17 inches	25.00	1	https://i.etsystatic.com/34112083/r/il/f04cea/6991166636/il_fullxfull.6991166636_mqdx.jpg	\N
74	Whimsigoth Dragonfly Auburn Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind auburn beaded necklace choker! The beaded design and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 17 inches	17.89	1	https://i.etsystatic.com/34112083/r/il/3feb5f/6462412914/il_fullxfull.6462412914_p3qv.jpg	\N
75	Whimsigoth Sun Pendant Earrings in gold | Fairycore | Whimsical	These are dangling simple and light weigh sun charm’s earrings in gold tones-  Perfect for any day wear or a special occasion.	9.50	1	https://i.etsystatic.com/34112083/r/il/a1011b/5639336145/il_fullxfull.5639336145_p863.jpg	\N
76	Whimsitwee Silver Dragonfly Floral  Keychain | Cottagecore | Goblincore |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	12.95	1	https://i.etsystatic.com/34112083/r/il/cca323/7053025383/il_fullxfull.7053025383_fh8b.jpg	\N
77	Whimsitwee Dragonfly Aquamarine Beaded necklace in Silver | Fairycore | Whimsicle | naturalist |	This is a one of a kind Aquamarine  beaded necklace choker! The beaded design and silver combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-17 inches	18.50	1	https://i.etsystatic.com/34112083/r/il/fdbe1c/6987109762/il_fullxfull.6987109762_sxnx.jpg	\N
78	Whimsigoth | Witchcraft | Fairy | Crystal Amethyst Crescent Moon  Necklace in Bronze	This is a beautiful raw amethyst crystal dangling from a crescent moon. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  EACH AMETHYST STONE IS UNIQUE IN SHAPE AND COLOR— PLEASE BE MINDFUL NOT EVERY NECKLACE WILL BE IDENTICAL TO THE SAME AND COLOR OF THE IMAGE SHOWN—	14.00	1	https://i.etsystatic.com/34112083/r/il/c39b79/6547966411/il_fullxfull.6547966411_joz9.jpg	\N
79	Whimsigoth Bohemian Maple Leaf Coffee Bean Fall Earrings in Bronze | Fairycore | Whimsical	These are dangling simple and light weigh maple leaf earrings bronze tones- Resin Beads   Perfect for any day wear or a special occasion.	12.75	1	https://i.etsystatic.com/34112083/r/il/786d07/7042316666/il_fullxfull.7042316666_sf5c.jpg	\N
80	Whimsigoth Maple Leaf Fall Earrings in Bronze | Fairycore | Whimsical	These are dangling simple and light weigh maple  earrings in bronze tones-  Perfect for any day wear or a special occasion.	9.50	1	https://i.etsystatic.com/34112083/r/il/02d03e/6884517950/il_fullxfull.6884517950_k9j0.jpg	\N
81	SALE Evil Eye crystal necklace in silver tone | statement piece| witchcraft jewelry |Wicca | Pagan	This hand crafted wire wrapped purple agate crystal necklace is paired as a dangling duo beautifully accented with a large size evil eye / Horus charm and 2 mini stars - such a fun and unique design. Silver tones!  Ready to ship	10.00	1	https://i.etsystatic.com/34112083/r/il/6a7145/4662166340/il_fullxfull.4662166340_j3o2.jpg	\N
82	Whimsigoth Bronze Sun Deep Green Beaded Necklace with Star Accents | Celestial | Whimsical | Vampy Goth |	This necklace is nickel free bronze with beautiful green and champagne glass beads. Handmade and lightweight. Jewelry Care! Keep away from moisture and water to keep metal from tarnish 💚	18.95	1	https://i.etsystatic.com/34112083/r/il/86c5aa/6553808066/il_fullxfull.6553808066_efxb.jpg	\N
101	Whimsigoth Amethyst Crystal Heart Pendant Necklace with Stainless Steel Chain	Free shipping on orders over $35  This is our amethyst heart crystal necklace in silver tone. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  Length- 18”   The stone pendants are natural so each crystal varies in color and overall shape.	14.50	1	https://i.etsystatic.com/34112083/r/il/806b46/5655261742/il_fullxfull.5655261742_1bd4.jpg	\N
83	Celestial Sun moon crescent amethyst crystal necklace with stainless steel chain | Pagan | Witchcraft | Fairy	This is our sun- moon- crescent amethyst crystal necklace in silver tone. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  Length- 18”  Amethyst is Known as “the all purpose stone”, Amethyst is a protective stone that helps to relieve stress and anxiety in your life, and the symptoms that accompany it, namely headaches, fatigues, and anxiety. It also aids in cell regeneration (supporting your bones and joints) and is reputed to improve your skin.	16.50	1	https://i.etsystatic.com/34112083/r/il/c4f8bc/5511365157/il_fullxfull.5511365157_mobd.jpg	\N
84	Handmade Pentacle Moon Trinity Earrings	This is a handmade moon trinity earring, simple wear yet dainty on the ear. Very light weight and easy to wear on the ear. It’s not heavy and it doesn’t tug and pull on the ear.	10.00	1	https://i.etsystatic.com/34112083/r/il/16b59a/3749922124/il_fullxfull.3749922124_d5ar.jpg	\N
85	Pentacle Moon Trinity Earrings… Wicca jewelry	This is a handmade moon trinity dangling earring, simple wear yet dainty on the ear. A perfect silver tone  earring duo that pairs perfectly with other jewelry or as a stand alone. Very light weight and easy to wear on the ear. It’s not heavy and it doesn’t tug and pull on the ear.  Ready to ship- fast ship   Custom orders welcome	10.00	1	https://i.etsystatic.com/34112083/r/il/fbf97f/3749918788/il_fullxfull.3749918788_crdq.jpg	\N
86	Whimsitwee Bronze Auburn Flower Beaded Necklace | Cottagecore | Whimsigoth | Bohemian	This necklace is perfect for anyone! Super lightweight and has a resin flower pendant  The necklace is nickel free alloy so please keep away from any type of moisture! Length— 16-17in	16.00	1	https://i.etsystatic.com/34112083/r/il/a151af/6975774708/il_fullxfull.6975774708_ic3q.jpg	\N
87	Amethyst Crystal Beaded Necklace Choker with Sun Pendant in Bronze | Fairycore | Whimsigoth | Wicca |	NATURAL STONE BEADS COLORS MAY VARY —  This is a one of a kind amethyst beaded necklace choker! The purple and bronze combination is beautiful. This necklace is handmade and quick shipping!	22.75	1	https://i.etsystatic.com/34112083/r/il/f0aecc/7149023797/il_fullxfull.7149023797_tj6j.jpg	\N
88	Misadventures Inspired O Ring Keychain | Emo | Scene | PTV	ONE KEYCHAIN PER PURCHASE— Pierce the Veil Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat— Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	12.00	1	https://i.etsystatic.com/34112083/r/il/85e461/7101052356/il_fullxfull.7101052356_lc30.jpg	\N
89	Misadventures Inspired Beaded Keychain | Emo | Scene | Punk | PTV |	ONE KEYCHAIN PER PURCHASE— Pierce the Veil Inspired Keychain— —Charm Material: PLA 3D Printed Resin Top Coat— Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	15.55	1	https://i.etsystatic.com/34112083/r/il/6204f6/7101047150/il_fullxfull.7101047150_kfpy.jpg	\N
90	Whimsigoth Floral Daisy Flower Dangling Necklace in 18k Gold Plated Stainless Steel | Fairycore | Cottagecore	This necklace is a chandelier style with an acrylic daisy flower.  The necklace is 18k gold plated stainlesss steel which means these earrings are tarnish resistant and heavy duty!   These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible.	17.50	1	https://i.etsystatic.com/34112083/r/il/242bba/5546391123/il_fullxfull.5546391123_iwbb.jpg	\N
91	Fairy Pearl Beaded Earrings with Butterfly charms | Fairycore | Whimsigoth | Goblincore	These are a dangling style silver toned earrings that are accented with beads. Easy to wear and fast shipping!	10.50	1	https://i.etsystatic.com/34112083/r/il/79cd09/4811794311/il_fullxfull.4811794311_8yie.jpg	\N
92	Bronze Sun and Moon Beaded Necklace with Black Bead Accents | Whimsigoth | Gothic |	This beaded necklace is a perfect blend of bronze and black beads. The sun and moon charms complement the necklace perfectly. This piece is lightweight and comfortable.  16-18 inches	18.88	1	https://i.etsystatic.com/34112083/r/il/f6ff8c/6753772387/il_fullxfull.6753772387_ayp8.jpg	\N
93	Gothic Floral Barbed Wire Ankh Beaded Necklace in Silver | Whimsigoth | Victorian |	This is a one of a kind  beaded necklace choker! The black and silver combination is beautiful with spiders to accent it. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-17 inches	22.50	1	https://i.etsystatic.com/34112083/r/il/686937/7015530309/il_fullxfull.7015530309_p5p0.jpg	\N
94	Bronze beaded Auburn brown and champagne sun, stars and moon necklace | Celestial | Whimsical | Vampy Goth |	This necklace is nickel free bronze with beautiful auburn and champagne glass beads in cut glass, crescent moons and star with bronze beads and bronze stars. Handmade and lightweight.     Jewelry Care! Keep away from moisture and water to keep metal from tarnish 💚	17.25	1	https://i.etsystatic.com/34112083/r/il/b6493a/7085010687/il_fullxfull.7085010687_fslm.jpg	\N
95	Victorian Red Trumpet Flower Chandelier Beaded Necklace in Bronze| Fairycore | Whimsigoth | Whimsitwee |	This is a one of a kind trumpet flower beaded necklace! The trumpet flower is an acrylic material and the beads are acrylic as well.  Keep away from moisture! Length: 16-17in	24.50	1	https://i.etsystatic.com/34112083/r/il/b4eabb/6967048304/il_fullxfull.6967048304_lmt6.jpg	\N
96	CLEARANCE— Goth Skull Blood drop Beaded Necklace in Bronze| Grunge | Whimsigoth | Gothic |	This is a one of a kind skull beaded necklace! The black and bronze combination is beautiful with bone toned mini skull beads to accent. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-17 inches	11.75	1	https://i.etsystatic.com/34112083/r/il/e8c3b1/6482524018/il_fullxfull.6482524018_dpim.jpg	\N
97	Fairy Bronze Mushroom Earrings | Fairycore | Whimsigoth | Goblincore	These are a dangling style bronze mushroom earrings are perfect with anything! Easy to wear and fast shipping!	10.00	1	https://i.etsystatic.com/34112083/r/il/bc0547/4637187818/il_fullxfull.4637187818_7sxp.jpg	\N
98	Whimsigoth Bronze Golden Lily of the Valley Keychain| Whimsitwee | Gothic |	ONE KEYCHAIN PER PURCHASE— This keychain is designed for a whimsical addition to any bag or outfit. Spice up business casual badges by adding a touch of whimsy. Add this piece to Backpacks, Purses, Work Badges, Jean Loops, Belts and many more!!	10.00	1	https://i.etsystatic.com/34112083/r/il/bef27a/6960783557/il_fullxfull.6960783557_8oth.jpg	\N
99	Whimsical Beaded Necklace Choker with Sun and Moon Pendant in Bronze | Fairycore | Whimsigoth | Wicca |	Length— 16-17in   This is a one of a kind beaded necklace choker! The purple and bronze combination is beautiful. This necklace is handmade and quick shipping!	20.00	1	https://i.etsystatic.com/34112083/r/il/cb8b22/6661504994/il_fullxfull.6661504994_idqz.jpg	\N
102	Celestial star round beads, 50 piece set, star design in neutral tones , beads for jewelry making/ beaded necklace bracelet beads diy	celestial star design round beads in boho inspired design, wood look but resin beads for a diy crafter. neutral toned,  Beads include 50 of the same bead.   - 50 piece set  - round beads with multiple star designs /  beads for jewelry making/ beaded necklace bracelet beads diy	3.75	1	https://i.etsystatic.com/34112083/r/il/5463ef/6549302116/il_fullxfull.6549302116_j0dv.jpg	\N
103	Fairy Butterfly Blue Iridescent Beaded Necklace in Bronze| Fairycore | Whimsigoth | naturalist |	This is a one of a kind butterfly beaded necklace! These iridescent blue beads and the bronze combination is beautiful. This necklace is handmade and quick shipping!  Length: 16-17in	17.50	1	https://i.etsystatic.com/34112083/r/il/2f31dc/6960789503/il_fullxfull.6960789503_lg8k.jpg	\N
104	Whimsical Champange Beaded Choker with Stars and Moon Pendant in Bronze | Fairycore | Whimsigoth | Wicca |	All orders over 35 dollars get free shipping!   This is a one of a kind beaded necklace choker! The purple and bronze combination is beautiful. This necklace is handmade and quick shipping!	16.50	1	https://i.etsystatic.com/34112083/r/il/55cc14/6806297187/il_fullxfull.6806297187_idtq.jpg	\N
105	Whimsigoth Daisy Humming Bird Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind beaded necklace ! The auburn and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 17-19 inches	17.89	1	https://i.etsystatic.com/34112083/r/il/23dd3b/6781936665/il_fullxfull.6781936665_bb1n.jpg	\N
106	Bronze Goddess Moon Trinity Pentacle Dangling Earrings	This is a handmade moon trinity earring, simple wear yet dainty on the ear. Very light weight and easy to wear on the ear. It’s not heavy and it doesn’t tug and pull on the ear.	10.00	1	https://i.etsystatic.com/34112083/r/il/f1e710/3671483309/il_fullxfull.3671483309_2er3.jpg	\N
107	Genuine Tigereye Crystal Beaded Necklace in Gold | Fairycore | Whimsigoth | Cottagecore |	This is a one of a kind Tigereye heart beaded necklace! The Brown and Gold combination is beautiful -This necklace is handmade and quick shipping! This also comes with a heart clasp! 17-18 in length  WARNING! The tigereye beads AND pendant are natural stones. This means that they very in shape, size and color. Please be mindful of this before purchasing!	18.95	1	https://i.etsystatic.com/34112083/r/il/bc96da/7103536957/il_fullxfull.7103536957_pkxk.jpg	\N
108	Pagan Pentagram Moon Trinity Auburn Foral Beaded Necklace in Bronze | Fairycore | Whimsigoth | Wicca |	This is a one of a pentagram beaded necklace! The green and bronze combination is beautiful with a gold pentagram pendent -This necklace is handmade and quick shipping!  16 in-17 in length	18.75	1	https://i.etsystatic.com/34112083/r/il/7eeb15/7055555194/il_fullxfull.7055555194_dc4i.jpg	\N
109	Celtic | Viking | Bronze Arrow Head Brown Cord Necklace	This necklace is perfect for anyone! The natural raw agate arrow head wears easy on the neck with the black cord necklace. Easy to wear and Fast shipping!	10.50	1	https://i.etsystatic.com/34112083/r/il/43aaa4/6642477568/il_fullxfull.6642477568_2oie.jpg	\N
110	Whimsigoth Maple Leaf Fall Earrings in Bronze/Gold | Fairycore | Whimsical	These are dangling simple and light weigh maple  earrings in gold tones or bronze tones-  — Made with Acrylic Beads 🍂 Perfect for any day wear or a special occasion.	12.30	1	https://i.etsystatic.com/34112083/r/il/b8f916/6649347869/il_fullxfull.6649347869_fsms.jpg	\N
111	Gothic Grunge Chandelier Bat  Earrings in Silver and Clear Quartz | Goth | Whimsical	These dangling earrings are chandelier style with accented auburn beads in silver.  Perfect for any day wear or a special occasion. We ship as fast as possible and these are made of a nickel free alloy so be mindful of tarnishing if exposed to moisture.  ( DUE TO THE CRYSTAL THESE  EARRINGS ARE SLIGHTLY HEAVIER THAN A STANDARD PAIR OF CHANDLER EARRINGS PLEASE BE MINDFUL BEFORE PURCHASING 💚)	14.50	1	https://i.etsystatic.com/34112083/r/il/ed450e/5905434639/il_fullxfull.5905434639_roqj.jpg	\N
112	Whimsigoth Hummingbird Floral Daisy Earrings | Naturalist | Gift for mom |	These Earrings are a beautiful mix of green bronze and white. They are lightweight and easy to wear. Avoid any areas that are high moisture to keep the necklace from tarnishing.	12.00	1	https://i.etsystatic.com/34112083/r/il/e54d65/6461963493/il_fullxfull.6461963493_sndg.jpg	\N
113	Whimsigoth Bloodstone Crystal Heart Pendant Necklace with Stainless Steel Chain	PRODUCT CONTAINS ONE NECKLACE! PHOTO IS TO SHOW THE COLOR VARIANTS OF THE NATURAL STONE :)—  This is our bloodstone heart crystal necklace in silver tone. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  Length- 18”   The stone pendants are natural so each crystal varies in color and overall shape.	14.50	1	https://i.etsystatic.com/34112083/r/il/40bc62/6664056199/il_fullxfull.6664056199_gfps.jpg	\N
114	Gothic Red Blood Drop Ankh Beaded Necklace with Bronze | Whimsigoth | Victorian |	This is a one of a kind  beaded necklace choker! The red and bronze combination is beautiful with moons to accent it. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 16-17 inches	16.00	1	https://i.etsystatic.com/34112083/r/il/bc9fae/6606504512/il_fullxfull.6606504512_6ejn.jpg	\N
115	Whimsigoth Clear Quartz Crystal Heart Pendant Necklace with Stainless Steel Chain	Free shipping on orders over $35  This is our clear quartz heart crystal necklace in silver tone. It’s a pendant style necklace perfect for spiritual individual or someone who loves astrology. Easy to wear and quick shipping!  Length- 18”   The stone pendants are natural so each charm varies in color and overall shape.	14.50	1	https://i.etsystatic.com/34112083/r/il/81e570/5511395287/il_fullxfull.5511395287_eig8.jpg	\N
116	Gothic Style Tiered Moonstone Crystal Beaded Necklace in Silver | Whimsigoth | Victorian |	This is a one of a kind tiered beaded necklace choker! The black and silver combination is beautiful with moonstone to accent it. This necklace is handmade and quick shipping! The chain is stainless steel while the pendant is a nickel free alloy.  Each necklace will have different unique color variations and sizes - Around 16-17 inches	13.50	1	https://i.etsystatic.com/34112083/r/il/2453e1/5675858348/il_fullxfull.5675858348_h5m5.jpg	\N
117	Romantic Goth Pendant Locket Beaded Necklace in Silver | Gothic | Whimsigoth | Alternative Jewelry	This necklace is a beautiful combination of silver, mauve and black resin beads. It is lightweight and comfortable to wear. — The locket is between 0.5-0.75in long. Any photo fits perfectly in this necklace.  — Pictures of loved ones or pets are a great addition to this piece.  The material is a nickel free alloy and a stainless steel chain so be mindful to tarnishing and keep away from high moisture areas. Length: 16-17 inches	23.50	1	https://i.etsystatic.com/34112083/r/il/1c93d0/6991179794/il_fullxfull.6991179794_lc3y.jpg	\N
118	Raw Crystal Amazonite Crescent Moon Necklace in Gold |fairy jewelry | cottagecore necklace |goblin core | whimsigoth	Our unique raw amazonite crescent moon necklace is a lightweight necklace- gold tones a perfect layering necklace or as s stand alone style.   Length 18”  Ready to ship	7.00	1	https://i.etsystatic.com/34112083/r/il/bbdd2d/5511334627/il_fullxfull.5511334627_881x.jpg	\N
119	Whimsigoth Mushroom Beaded Necklace in Gold | Goblincore | Cottagecore |	This necklace is a beautiful mix of gold metal and red beads. The metal is gold plated stainless steel and nickel free alloy so keep away from high moisture areas. The necklace length is between 16-17 inches.	16.50	1	https://i.etsystatic.com/34112083/r/il/eb8303/7039209849/il_fullxfull.7039209849_dh53.jpg	\N
120	Deep Green and Gold Celtic Triquetra Beaded Necklace in Silver | Fairycore | Whimsigoth | Wicca |	This is a one of a kind celtic beaded choker necklace! The Green and Gold combination is beautiful celtic pendent and moon charm accents -This necklace is handmade and quick shipping!    — Nickel Free Alloy  16- 17in length ( adjustable)	20.00	1	https://i.etsystatic.com/34112083/r/il/4553df/7039127905/il_fullxfull.7039127905_1xel.jpg	\N
121	Oceanic Sun Auburn & Blue Glass Beaded necklace in Bronze | | Whimsicle | naturalist | Oceancore	This is a one of a kind auburn beaded necklace choker! The beaded design and bronze combination is beautiful. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 17 inches	18.75	1	https://i.etsystatic.com/34112083/r/il/0d3d77/6961778080/il_fullxfull.6961778080_fhhc.jpg	\N
122	Bronze Heart Pendant Beaded Necklace in Burgundy | Gothic |Whimsigoth | Artsy | Alternative	This necklace is a perfect piece to pair either on its own or with our other pieces. It is lightweight and comfortable. The bronze and burgundy colors match perfectly to make an elegant appearance.  16-18 inches in length	17.50	1	https://i.etsystatic.com/34112083/r/il/a24fec/6095040368/il_fullxfull.6095040368_tm0x.jpg	\N
123	Moon Trinity Pentacle earrings-witchcraft jewelry/ pagan/ Celtic/ celestial / tree of life	Pentacle tree of life moon trinity earrings in silver tones as drop earrings-	10.00	1	https://i.etsystatic.com/34112083/r/il/fdc8da/5066434725/il_fullxfull.5066434725_ekxi.jpg	\N
124	Dainty mini Ankh bronze and emerald green beaded dangling earrings- small and dainty -	Dangling emerald green cut glass beaded bronze with mini 1/2 inch Ankh charm dangling earrings with lever back clasps.  earrings are 2’ in length and ankh charm dainty sized at 1/2 ‘.   The ankh symbol is from ancient Egyptian culture and thought of as “ the key of life “ and represents eternal life. Symbol of healing properties and associated with strength and prosperity, the ankh is said to be the first--or original--cross.  Ready to ship — with fast shipping	12.50	1	https://i.etsystatic.com/34112083/r/il/48fe01/6967608032/il_fullxfull.6967608032_bari.jpg	\N
125	Whimsitwee Bronze green Flower Cord Necklace | Cottagecore | Whimsigoth | Bohemian	This dainty flower pendant necklace is a light mossy green sheer color with bronze accent beads-  necklace is perfect for anyone! Super lightweight and  Easy to wear or pair with other jewelry ! PLUS Fast shipping	13.50	1	https://i.etsystatic.com/34112083/r/il/bc7b8f/6967500364/il_fullxfull.6967500364_jf2l.jpg	\N
126	Whimsigoth Floral Lily of the Valley Flower Dangling Rose Gold Earrings  | Fairycore | Whimsical	These dangling earrings are chandelier style with an acrylic lily flower.  These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	15.50	1	https://i.etsystatic.com/34112083/r/il/fca56e/5775821086/il_fullxfull.5775821086_hnr1.jpg	\N
127	Whimsitwee Lily of the Valley Flower Dangling Chandelier Earrings in 18k Gold Plated Stainless Steel | Fairycore | Cottagecore	These dangling earrings are chandelier style with an acrylic lily flower.  18k Gold Plated Stainless Steel— Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	17.50	1	https://i.etsystatic.com/34112083/r/il/beb784/6962596314/il_fullxfull.6962596314_tk70.jpg	\N
128	Ankh necklace in silver tones on black cord necklace	Silver Ankh pendent on a black  cord necklace-  The ankh symbol is from ancient Egyptian culture and thought of as “ the key of life “ and represents eternal life. Symbol of healing properties and associated with strength and prosperity, the ankh is said to be the first--or original--cross.  Ready to ship — also available in bronze	12.00	1	https://i.etsystatic.com/34112083/r/il/42655d/4009636345/il_fullxfull.4009636345_pb1b.jpg	\N
129	Whimsigoth Mushroom Green Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind mushroom beaded necklace! The green and bronze combination is beautifu. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 17-18 inches	17.50	1	https://i.etsystatic.com/34112083/r/il/28f0dd/6884512210/il_fullxfull.6884512210_aivz.jpg	\N
130	Grunge Pentagram Serpentine Skull Sword Beaded Necklace | Gothic | Alternative	This necklace is lightweight and comfortable to wear. The necklace is a mix of Stainless Steel and Nickel free alloy so keep away from high humidity and water. The piece is between 16-17 inches in length.	17.50	1	https://i.etsystatic.com/34112083/r/il/d33073/6207131385/il_fullxfull.6207131385_fq1o.jpg	\N
131	Whimsigoth Bronze Floral Hand Boutique Lily of the Valley Necklace | Whimsical | Floral Jewelry |	Lily of the valley bronze necklace! Beautiful combination of bronze and pearl!  Keep away from high moisture areas  Length 17-18in	18.50	1	https://i.etsystatic.com/34112083/r/il/1ff9fa/6940306574/il_fullxfull.6940306574_1d6j.jpg	\N
132	Whimsigoth Mushroom Auburn Beaded necklace in Bronze | Fairycore | Whimsicle | naturalist |	This is a one of a kind auburn beaded necklace choker! The fed and bronze combination is beautifu. This necklace is handmade and quick shipping!  Each necklace will have different unique color variations and sizes - Around 17-18 inches	16.50	1	https://i.etsystatic.com/34112083/r/il/a8cd8a/6720314840/il_fullxfull.6720314840_hekl.jpg	\N
133	Whimsigoth Floral Lily Dragonfly Flower Dangling Earrings in Bronze| Fairycore | Whimsical	These dangling earrings are chandelier style with an acrylic lily flower. These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible.	14.75	1	https://i.etsystatic.com/34112083/r/il/6d116a/6603688532/il_fullxfull.6603688532_kmuf.jpg	\N
134	Whimsigoth Floral Lucite Flower Dangling Earrings in Bronze | Fairycore | Whimsical	These dangling earrings are chandelier style with an acrylic lucite flower.  These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	12.50	1	https://i.etsystatic.com/34112083/r/il/15e2bd/5655234234/il_fullxfull.5655234234_ko8n.jpg	\N
135	Sunflower Glass Beaded necklace in Gold | Fairycore | Whimsigoth | Wicca |	This is a one of a kind glass beaded necklace with sunflower pendant! The champagne and gold tone combination is beautiful. Necklace has glass beads paired with a sunflower pendant-	16.50	1	https://i.etsystatic.com/34112083/r/il/598879/6649641973/il_fullxfull.6649641973_j69b.jpg	\N
136	Whimsigoth Floral Bouquet Flower Dangling Rose Gold Earrings  | Fairycore | Whimsical	These dangling earrings are chandelier style with an acrylic flower.  These are SUPER lightweight and so beautiful:) Perfect for any day wear or a special occasion. We ship as fast as possible and we take custom orders as well just message if interested.	12.50	1	https://i.etsystatic.com/34112083/r/il/3adce8/6965526385/il_fullxfull.6965526385_ndin.jpg	\N
137	Whimsigoth Carnelian Chandelier Sun Pendant Earrings in Gold | Fairycore | Whimsical	These dangling earrings are chandelier style with genuine sodalite crystal and sun pendant in silver.  Perfect for any day wear or a special occasion.	12.00	1	https://i.etsystatic.com/34112083/r/il/43358d/6917552020/il_fullxfull.6917552020_mwjp.jpg	\N
138	Sunflower Glass Beaded necklace in Gold | Fairycore | Whimsigoth | Wicca |	This is a one of a kind glass beaded necklace with sun pendant! The pearl and gold tone combination is beautiful. Necklace has glass beads paired with a sunflower pendant-	16.50	1	https://i.etsystatic.com/34112083/r/il/17ce2f/6668331741/il_fullxfull.6668331741_guww.jpg	\N
139	Bronze Ankh Cord Necklace- large size	Bronze Ankh pendent on a dark brown cord necklace-  The ankh symbol is from ancient Egyptian culture and thought of as “ the key of life “ and represents eternal life. Symbol of healing properties and associated with strength and prosperity, the ankh is said to be the first--or original--cross.  Ready to ship — also available in silver tone	12.00	1	https://i.etsystatic.com/34112083/r/il/9da1df/4455816823/il_fullxfull.4455816823_8442.jpg	\N
140	Pearlescent Large Dangling Earrings in bronze	These are cute and dainty pair of earrings and perfect for any occasion. Light weight and easy to wear on the ear.  “Sold separate from necklace “   Ready to ship Free shipping with orders over $35	12.00	1	https://i.etsystatic.com/34112083/r/il/c60eb3/4408536008/il_fullxfull.4408536008_de44.jpg	\N
141	Whimsigoth Auburn and Amethyst Bronze Sun Beaded Necklace with Sun & Leaf Accents | Celestial | Whimsical | Vampy Goth |	This necklace is nickel free bronze with beautiful auburn glass beads and authentic amethyst beads. Handmade and lightweight. Jewelry Care! Keep away from moisture and water to keep metal from tarnish 💚	19.95	1	https://i.etsystatic.com/34112083/r/il/2fcf4d/6801895633/il_fullxfull.6801895633_blna.jpg	\N
142	Whimsigoth Sodalite Chandelier Sun Pendant Earrings in Silver | Fairycore | Whimsical	These dangling earrings are chandelier style with genuine sodalite crystal and sun pendant in silver.  Perfect for any day wear or a special occasion.	12.00	1	https://i.etsystatic.com/34112083/r/il/bf48af/5461134046/il_fullxfull.5461134046_a74t.jpg	\N
143	Whimsigoth Pink Lily and White Daisy Beaded Necklace in Silver with Green Accents | Fairycore | Naturalist	This is a one of a kind statement piece beaded necklace! The pink and silver combination is beautiful. This necklace is handmade and quick shipping!  17” length	18.50	1	https://i.etsystatic.com/34112083/r/il/22127e/6581291512/il_fullxfull.6581291512_i33n.jpg	\N
144	Tree of life 18k Gold Stainless Steel aventurine crystal necklace	This is our green aventurine crystal necklace in our tree of life design in gold tones. Quality rope style chain that’s 18” long.  Aventurine Metaphysical Properties Think bountiful. Think practical enthusiasm. This stone is believed to be a positive stone of prosperity, diffusing negative emotions, reinforcing leadership, promoting compassion and encouraging perseverance.	16.50	1	https://i.etsystatic.com/34112083/r/il/d8d3c6/4012093487/il_fullxfull.4012093487_4t3l.jpg	\N
\.


--
-- TOC entry 3389 (class 0 OID 0)
-- Dependencies: 225
-- Name: product_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.product_product_id_seq', 144, true);


-- Completed on 2025-09-16 22:04:23

--
-- PostgreSQL database dump complete
--

\unrestrict HhgrfQrsZNOCZwo4xdaPWGhUKaJwRUmQAf3dk7jGmHZlbBck2YrKPHItP1q8tMA

